//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracionCliente
    {
        public int id { get; set; }
        public string valor { get; set; }
        public int idConfiguracion { get; set; }
        public int idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual configuracion configuracion { get; set; }
    }
}
