//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class informacionEmpleadoEmpleado
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public int idInformacionEmpleado { get; set; }
        public string valor { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual informacionEmpleado informacionEmpleado { get; set; }
    }
}
