//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoAdicional
    {
        public int id { get; set; }
        public string atributo { get; set; }
        public string valor { get; set; }
        public string tipo { get; set; }
        public bool requerido { get; set; }
        public bool vigente { get; set; }
        public int idPersona { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
