//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class informacionAfiliado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public informacionAfiliado()
        {
            this.informacionAfiliadoAfiliado = new HashSet<informacionAfiliadoAfiliado>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string atributo { get; set; }
        public string tipoValor { get; set; }
        public bool requerido { get; set; }
        public bool vigente { get; set; }
        public int idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<informacionAfiliadoAfiliado> informacionAfiliadoAfiliado { get; set; }
    }
}
