//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class paqueteActividad
    {
        public int id { get; set; }
        public int idPaquete { get; set; }
        public int idActividad { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual paquete paquete { get; set; }
    }
}
