//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freed.Servicios.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int id { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public int idCliente { get; set; }
        public int idRol { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual rol rol { get; set; }
        public virtual tipoNomina tipoNomina { get; set; }
    }
}
